INFO = "Log.INFO"
DEBUG = "Log.DEBUG"
ERROR = "Log.ERROR"
FATAL = "Log.FATAL"
WARN = "Log.WARN"
VERBOSE = "Log.VERBOSE"
ALL = "Log.ALL"

AIR = "Log.AIR"
DRONE_DETAILS = "Log.DRONE_DETAILS"
ROOT_DRONE_ONLY = "Log.ROOT_DRONE_ONLY"

Levels = {
    FATAL: 0,
    ERROR: 1,
    INFO: 2,
    WARN: 3,
    DEBUG: 4,
    VERBOSE: 5,
    ALL: 99
}
