INFO = "Log.INFO"
DEBUG = "Log.DEBUG"
TRACE = "Log.TRACE"
ERROR = "Log.ERROR"
FATAL = "Log.FATAL"
WARN = "Log.WARN"
VERBOSE = "Log.VERBOSE"
ALL = "Log.ALL"

EXCLUSIVE = "Log.EXCLUSIVE"
SHOW_LEVEL = "Log.SHOW_LEVEL"
REPR = "Log.REPR"
PRINT_APS = "Log.PRINT_APS"

AIR = "Log.AIR"
DRONE_DETAILS = "Log.DRONE_DETAILS"

Levels = {
    FATAL: 0,
    ERROR: 1,
    WARN: 2,
    INFO: 3,
    TRACE: 4,
    DEBUG: 5,
    VERBOSE: 5,
    ALL: 99
}
